### ISSUE TITLE
Question about device-setup

### ISSUE THREAD

**Issue by andrasj** [BWiebe1/openexcavator#1]
Hi,
I am implementing a driver for RTIMULib for the ICM20948 which is in the ReachRS2. That's how I found your imud-repo and also this openexcavator. I've some questions related to the setup:
* Am I correct you're mounting the RTK-receiver directly on the bucket? (I cannot imagine a 'safe' place where it won't be hit by obstacles)
* Is this working well 'in the field' with the L1-receiver only?

**Comment by iticus** [comment]
Hi,

I only ran tests using my own contraption (without an actual excavator), but if I remember correctly the receiver was mounted directly on the bucket; I think @BWiebe1 has a video of the setup.

Regarding using a single receiver (instead of a station/rover setup) the accuracy will probably be affected quite a lot.
The web application (openexcavator) will show accuracy/fix data coming from the GPS receiver.

There hasn't been much development on this project lately mainly due to updates to the Reach firmware which prevented the IMU data from being accessed but from what I understand with the new chip in the RS2 the data is again available under the regular user on the SPI bus.

**Comment by andrasj** [comment]
Tnx for the info.
I didn't mean a rover-only, but a single-frequency rover (like the ReachRS instead of RS2).With my reach modules, it takes ages to get a 'Fix'-solution, and it is lost very fast.
I got RTIMMULib working on the RS2, but the new problem is: getting some process started to get the data out. (I'm afraid we need to look for some auto-login and start some process)

**Comment by iticus** [comment]
I don't have access to an RS2 unit yet; in old firmware versions one had access to the root account and could define services (using systemd) to run at startup.
In newer versions end-users could only access a regular account and could not access the SPI bus (in order to get IMU data).
